GET http://localhost:5000/api/v1/user/ads

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "email": "testuser1@gmail.com",
  "password": "123123"
}


###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "testuser1@gmail.com",
  "password": "123123"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjMiLCJpYXQiOjE3NDgxOTUxNjksImV4cCI6MTc0ODE5NTE3NH0.bMiYF2tqNUSt062cBkOPDAJbiwFoYh4IDYZabhUAOv8

###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/